import type { Post, PostSlideData } from "@/lib/types";

// ==================== Post 타입 더미 데이터 ====================
// PostCard 컴포넌트 테스트용 (Phase2에서 API로 대체)
export const mockPosts: Post[] = [
  {
    id: "post-1",
    slug: "nextjs-15-app-router-guide",
    title: "Next.js 15 App Router 완벽 가이드",
    description:
      "App Router의 핵심 개념인 Server Components, Layouts, Loading UI를 실전 예제로 알아봅니다.",
    category: {
      id: "cat-1",
      name: "Next.js",
      slug: "nextjs",
      color: "blue",
      count: 3,
    },
    tags: [
      { id: "tag-1", name: "Next.js", slug: "nextjs", color: "blue", count: 5 },
      { id: "tag-2", name: "React", slug: "react", color: "cyan", count: 8 },
      { id: "tag-3", name: "성능최적화", slug: "performance", color: "green", count: 4 },
    ],
    publishedDate: "2026-04-20",
    modifiedDate: "2026-04-25",
    status: "발행됨",
    featured: true,
    coverImage: null,
    notionPageId: "notion-1",
  },
  {
    id: "post-2",
    slug: "tailwind-css-v4-design-system",
    title: "Tailwind CSS v4로 디자인 시스템 구축하기",
    description: "CSS-first 접근 방식의 Tailwind CSS v4를 활용해 일관된 디자인 토큰과 컴포넌트를 만드는 방법을 소개합니다.",
    category: {
      id: "cat-2",
      name: "CSS",
      slug: "css",
      color: "purple",
      count: 2,
    },
    tags: [
      { id: "tag-4", name: "CSS", slug: "css", color: "purple", count: 6 },
      { id: "tag-5", name: "Tailwind", slug: "tailwind", color: "cyan", count: 7 },
    ],
    publishedDate: "2026-04-15",
    modifiedDate: "2026-04-20",
    status: "발행됨",
    featured: false,
    coverImage: null,
    notionPageId: "notion-2",
  },
  {
    id: "post-3",
    slug: "typescript-type-guards",
    title: "TypeScript 타입 가드와 좁히기 패턴",
    description: "복잡한 유니온 타입을 안전하게 처리하는 타입 가드 패턴과 실무에서 자주 만나는 케이스를 다룹니다.",
    category: {
      id: "cat-3",
      name: "TypeScript",
      slug: "typescript",
      color: "green",
      count: 4,
    },
    tags: [
      { id: "tag-6", name: "TypeScript", slug: "typescript", color: "green", count: 9 },
      { id: "tag-7", name: "타입안전성", slug: "type-safety", color: "blue", count: 3 },
    ],
    publishedDate: "2026-04-08",
    modifiedDate: "2026-04-15",
    status: "발행됨",
    featured: true,
    coverImage: null,
    notionPageId: "notion-3",
  },
  {
    id: "post-4",
    slug: "react-19-new-features",
    title: "React 19 새 기능 총정리",
    description: "React 19에서 추가된 useActionState, useFormStatus, 그리고 Server Actions의 변화를 정리합니다.",
    category: {
      id: "cat-4",
      name: "React",
      slug: "react",
      color: "cyan",
      count: 5,
    },
    tags: [
      { id: "tag-8", name: "React", slug: "react", color: "cyan", count: 8 },
      { id: "tag-9", name: "Hooks", slug: "hooks", color: "purple", count: 5 },
    ],
    publishedDate: "2026-04-01",
    modifiedDate: "2026-04-10",
    status: "발행됨",
    featured: false,
    coverImage: null,
    notionPageId: "notion-4",
  },
  {
    id: "post-5",
    slug: "zustand-state-management",
    title: "Zustand로 전역 상태 관리 간소화하기",
    description: "Redux의 복잡함 없이 간결하게 전역 상태를 관리하는 Zustand 패턴과 미들웨어 활용법을 살펴봅니다.",
    category: {
      id: "cat-4",
      name: "React",
      slug: "react",
      color: "cyan",
      count: 5,
    },
    tags: [
      { id: "tag-10", name: "상태관리", slug: "state-management", color: "orange", count: 4 },
      { id: "tag-11", name: "Zustand", slug: "zustand", color: "rose", count: 2 },
    ],
    publishedDate: "2026-03-28",
    modifiedDate: "2026-04-05",
    status: "발행됨",
    featured: false,
    coverImage: null,
    notionPageId: "notion-5",
  },
  {
    id: "post-6",
    slug: "nodejs-performance-optimization",
    title: "Node.js 성능 최적화 실전 가이드",
    description: "프로덕션 Node.js 애플리케이션의 성능 병목을 찾고 해결하는 프로파일링 기법과 최적화 전략을 소개합니다.",
    category: {
      id: "cat-5",
      name: "Node.js",
      slug: "nodejs",
      color: "rose",
      count: 1,
    },
    tags: [
      { id: "tag-12", name: "Node.js", slug: "nodejs", color: "rose", count: 4 },
      { id: "tag-13", name: "성능최적화", slug: "performance", color: "green", count: 4 },
    ],
    publishedDate: "2026-03-20",
    modifiedDate: "2026-03-28",
    status: "발행됨",
    featured: true,
    coverImage: null,
    notionPageId: "notion-6",
  },
  {
    id: "post-7",
    slug: "web-performance-metrics",
    title: "핵심 Web Performance 메트릭 이해하기",
    description: "LCP, FID, CLS 등 Core Web Vitals를 측정하고 개선하는 방법을 체계적으로 배웁니다.",
    category: {
      id: "cat-1",
      name: "Next.js",
      slug: "nextjs",
      color: "blue",
      count: 3,
    },
    tags: [
      { id: "tag-14", name: "성능", slug: "performance", color: "green", count: 6 },
      { id: "tag-15", name: "웹개발", slug: "web", color: "yellow", count: 10 },
    ],
    publishedDate: "2026-03-15",
    modifiedDate: "2026-03-22",
    status: "발행됨",
    featured: false,
    coverImage: null,
    notionPageId: "notion-7",
  },
  {
    id: "post-8",
    slug: "testing-strategies",
    title: "프론트엔드 테스트 전략과 도구",
    description: "Jest, Vitest, Playwright를 활용한 단위 테스트, 통합 테스트, E2E 테스트 실전 가이드입니다.",
    category: {
      id: "cat-6",
      name: "테스트",
      slug: "testing",
      color: "yellow",
      count: 2,
    },
    tags: [
      { id: "tag-16", name: "테스트", slug: "testing", color: "yellow", count: 5 },
      { id: "tag-17", name: "Playwright", slug: "playwright", color: "purple", count: 3 },
    ],
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-18",
    status: "발행됨",
    featured: false,
    coverImage: null,
    notionPageId: "notion-8",
  },
  {
    id: "post-9",
    slug: "docker-containerization",
    title: "Docker를 이용한 애플리케이션 컨테이너화",
    description: "Docker의 기본 개념부터 실무에서 사용하는 멀티 스테이지 빌드, 네트워킹까지 완벽 가이드입니다.",
    category: {
      id: "cat-7",
      name: "DevOps",
      slug: "devops",
      color: "orange",
      count: 3,
    },
    tags: [
      { id: "tag-18", name: "Docker", slug: "docker", color: "orange", count: 7 },
      { id: "tag-19", name: "DevOps", slug: "devops", color: "orange", count: 5 },
    ],
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-12",
    status: "발행됨",
    featured: false,
    coverImage: null,
    notionPageId: "notion-9",
  },
  {
    id: "post-10",
    slug: "graphql-vs-rest",
    title: "GraphQL과 REST API 비교: 실무 선택 가이드",
    description: "GraphQL과 REST API의 장단점을 비교하고 각 상황에 맞는 API 설계 패턴을 제시합니다.",
    category: {
      id: "cat-8",
      name: "API",
      slug: "api",
      color: "cyan",
      count: 2,
    },
    tags: [
      { id: "tag-20", name: "GraphQL", slug: "graphql", color: "cyan", count: 4 },
      { id: "tag-21", name: "API", slug: "api", color: "yellow", count: 8 },
    ],
    publishedDate: "2026-02-28",
    modifiedDate: "2026-03-08",
    status: "발행됨",
    featured: true,
    coverImage: null,
    notionPageId: "notion-10",
  },
];

// ==================== PostSlideData 더미 데이터 ====================
// 임시 더미 포스트 데이터 (개발/테스트용)
// Task 007에서 Notion API 연동 후 사용 중단
export const dummyPosts: PostSlideData[] = [
  {
    id: "1",
    title: "Next.js 15 App Router 완벽 가이드",
    description:
      "App Router의 핵심 개념인 Server Components, Layouts, Loading UI를 실전 예제로 알아봅니다. RSC 패러다임이 가져온 변화와 함께 성능 최적화 전략까지 심층적으로 다룹니다.",
    category: "Next.js",
    readingTime: "8분",
    publishedAt: "2026.04.20",
    slug: "nextjs-15-app-router-guide",
    colorTheme: "blue",
    index: 1,
  },
  {
    id: "2",
    title: "Tailwind CSS v4로 디자인 시스템 구축하기",
    description:
      "CSS-first 접근 방식의 Tailwind CSS v4를 활용해 일관된 디자인 토큰과 컴포넌트를 만드는 방법을 소개합니다.",
    category: "CSS",
    readingTime: "6분",
    publishedAt: "2026.04.15",
    slug: "tailwind-css-v4-design-system",
    colorTheme: "purple",
    index: 2,
  },
  {
    id: "3",
    title: "TypeScript 타입 가드와 좁히기 패턴",
    description:
      "복잡한 유니온 타입을 안전하게 처리하는 타입 가드 패턴과 실무에서 자주 만나는 케이스를 다룹니다.",
    category: "TypeScript",
    readingTime: "10분",
    publishedAt: "2026.04.08",
    slug: "typescript-type-guards",
    colorTheme: "green",
    index: 3,
  },
  {
    id: "4",
    title: "React 19 새 기능 총정리",
    description:
      "React 19에서 추가된 useActionState, useFormStatus, 그리고 Server Actions의 변화를 정리합니다.",
    category: "React",
    readingTime: "7분",
    publishedAt: "2026.04.01",
    slug: "react-19-new-features",
    colorTheme: "cyan",
    index: 4,
  },
  {
    id: "5",
    title: "Zustand로 전역 상태 관리 간소화하기",
    description:
      "Redux의 복잡함 없이 간결하게 전역 상태를 관리하는 Zustand 패턴과 미들웨어 활용법을 살펴봅니다.",
    category: "React",
    readingTime: "5분",
    publishedAt: "2026.03.28",
    slug: "zustand-state-management",
    colorTheme: "orange",
    index: 5,
  },
  {
    id: "6",
    title: "Node.js 성능 최적화 실전 가이드",
    description:
      "프로덕션 Node.js 애플리케이션의 성능 병목을 찾고 해결하는 프로파일링 기법과 최적화 전략을 소개합니다.",
    category: "Node.js",
    readingTime: "12분",
    publishedAt: "2026.03.20",
    slug: "nodejs-performance-optimization",
    colorTheme: "rose",
    index: 6,
  },
];
